config/routes.rb
Rails.application.routes.draw do
  root 'teas#index'
  resources :teas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tea.rb
class Tea < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/teas_controller.rb
class TeasController < ApplicationController
  before_action :set_tea, only: [:show, :edit, :update, :destroy]

  # GET /teas
  # GET /teas.json
  def index
    @teas = Tea.all
  end

  # GET /teas/1
  # GET /teas/1.json
  def show
  end

  # GET /teas/new
  def new
    @tea = Tea.new
  end

  # GET /teas/1/edit
  def edit
  end

  # POST /teas
  # POST /teas.json
  def create
    @tea = Tea.new(tea_params)

    respond_to do |format|
      if @tea.save
        format.html { redirect_to @tea, notice: 'Tea was successfully created.' }
        format.json { render :show, status: :created, location: @tea }
      else
        format.html { render :new }
        format.json { render json: @tea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teas/1
  # PATCH/PUT /teas/1.json
  def update
    respond_to do |format|
      if @tea.update(tea_params)
        format.html { redirect_to @tea, notice: 'Tea was successfully updated.' }
        format.json { render :show, status: :ok, location: @tea }
      else
        format.html { render :edit }
        format.json { render json: @tea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teas/1
  # DELETE /teas/1.json
  def destroy
    @tea.destroy
    respond_to do |format|
      format.html { redirect_to teas_url, notice: 'Tea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tea
      @tea = Tea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tea_params
      params.require(:tea).permit(:name, :description, :caffeine, :times_chosen, :times_skipped)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/teas_helper.rb
module TeasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Teapicker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/teas/_form.html.erb
<%= form_for(tea) do |f| %>
  <% if tea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tea.errors.count, "error") %> prohibited this tea from being saved:</h2>

      <ul>
      <% tea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :caffeine %>
    <%= f.text_field :caffeine %>
  </div>

  <div class="field">
    <%= f.label :times_chosen %>
    <%= f.number_field :times_chosen %>
  </div>

  <div class="field">
    <%= f.label :times_skipped %>
    <%= f.number_field :times_skipped %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teas/edit.html.erb
<h1>Editing Tea</h1>

<%= render 'form', tea: @tea %>

<%= link_to 'Show', @tea %> |
<%= link_to 'Back', teas_path %>

app/views/teas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Teas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Caffeine</th>
      <th>Times chosen</th>
      <th>Times skipped</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teas.each do |tea| %>
      <tr>
        <td><%= tea.name %></td>
        <td><%= tea.description %></td>
        <td><%= tea.caffeine %></td>
        <td><%= tea.times_chosen %></td>
        <td><%= tea.times_skipped %></td>
        <td><%= link_to 'Show', tea %></td>
        <td><%= link_to 'Edit', edit_tea_path(tea) %></td>
        <td><%= link_to 'Destroy', tea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tea', new_tea_path %>

app/views/teas/new.html.erb
<h1>New Tea</h1>

<%= render 'form', tea: @tea %>

<%= link_to 'Back', teas_path %>

app/views/teas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tea.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tea.description %>
</p>

<p>
  <strong>Caffeine:</strong>
  <%= @tea.caffeine %>
</p>

<p>
  <strong>Times chosen:</strong>
  <%= @tea.times_chosen %>
</p>

<p>
  <strong>Times skipped:</strong>
  <%= @tea.times_skipped %>
</p>

<%= link_to 'Edit', edit_tea_path(@tea) %> |
<%= link_to 'Back', teas_path %>